modLoader="javafml" #mandatory
loaderVersion="[32,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId="arknights" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Arknights Mod" #mandatory
updateJSONURL="https://github.com/TeamGrainPigeon/Minecraft-Arknights-Mod" #optional
displayURL="https://github.com/TeamGrainPigeon/Minecraft-Arknights-Mod" #optional
logoFile="arknights.png" #optional
credits="NGYF, Tao0Lu\n感谢黄金之匣美工社提供的干员皮肤，GrakePCH大佬的源石、合成玉模型\nThank Team The Gold Chest for the Operator Skin,GrakePCH for the originium and the orundum models." #optional
authors="NGYF, Tao0Lu" #optional
description='''

我的世界明日方舟mod，让明日方舟成为真正的方舟。
Minecraft Arknights Mod,show the Arknights in the Minecraft.

本mod为明日方舟爱好者所编写，与hypergryph(鹰角网络)和mojang没有任何附属关系。
mod开源且不收取任何费用，部分模型和文件来自开源项目，或者来源其他并已经授权。
由于黄金之匣美工社提供的干员皮肤遵循CC-BY-NC-SA 4.0协议，不得擅自用于商业用途。

This mod has no affiliation with hypergryph and mojang.
This mod is open source and free. Some models and files are from open source projects or from other sources and have been authorized.
As the skin provided by Team The Gold Chest follows the CC-BY-NC-SA 4.0 agreement, it shall not be used for commercial purposes without authorization.
'''

[[dependencies.arknights]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[32,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.arknights]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"